### ISSUE TITLE
关于摄像头

### ISSUE THREAD

**Issue by riven-zou** [frezs/MateBook14-Hackintosh#11]
请问现在摄像头优化好了吗？万分感激

**Comment by JuserZhang** [comment]
摄像头一直都可以使用啊

**Comment by riven-zou** [comment]
我的是linux版本，怎样装Win+Mac？可以指导一下吗？

**Comment by JuserZhang** [comment]
我的也是linux版本，如果先按照win在按照mac会导致按照失败，原因是mac要求要格式化整个磁盘，单个分区没办法按照，按照网上的教程不行，你可以反着来，首先全盘按照mac，然后在mac下划分一个分区按照win。这个方案本人验证可行。

**Comment by JuserZhang** [comment]
我的也是linux版本，如果先安装win在安装mac会导致按安装失败，原因是mac要求要格式化整个磁盘，单个分区没办法按照，按照网上的教程不行，你可以反着来，首先全盘安装mac，然后在mac下划分一个分区安装win。这个方案本人验证可行。

**Comment by riven-zou** [comment]
我们linux版本应该不是三星硬盘   可以按照网上的教程来吧？你是三星硬盘吗？

**Comment by riven-zou** [comment]
> 我的也是linux版本，如果先安装赢了在安装mac会导致按安装失败，原因是mac要求要格式化整个磁盘，单个分区没办法按照，按照网上的教程不行，你可以反着来，首先全盘安装mac，然后在mac下划分一个分区安装赢了。这个方案本人验证可行.

**Comment by riven-zou** [comment]
> 我的也是linux版本，如果先安装赢了在安装mac会导致按安装失败，原因是mac要求要格式化整个磁盘，单个分区没办法按照，按照网上的教程不行，你可以反着来，首先全盘安装mac，然后在mac下划分一个分区安装赢了。这个方案本人验证可行.

我们linux版本应该不是三星硬盘可以按照网上的教程来吧？你是三星硬盘吗？

**Comment by JuserZhang** [comment]
不是三星的，三星的根本安装不了。跟方法没关系。

**Comment by riven-zou** [comment]
这么坑爹--- 那您方便把你的硬盘   整盘备份给我吗？这样子我都不需要操作了直接覆盖到我硬盘就可以用了哈哈

**Comment by riven-zou** [comment]
406518553我的qq  可以qq聊吗？万分感谢

**Comment by JuserZhang** [comment]
我是macOS + deepin linux +win10，备份硬盘貌似不可行，还是得你自己折腾 qq：1365385081

**Comment by frezs** [comment]
双系统无损安装的的要点如下：
1、先安装Windows系统，并备份Windows的引导EFI分区的（EFI/Boot和Microsoft）。
2、调整EFI分区，使用DiskGenius将EFI分区调整为200M（没有则新建EFI分区，新建类型一定要选择EFI分区类型），可以将多余MSR分区删掉（强迫症）。EFI分区一般放在硬盘最前面，硬盘前端没有空间就先移动系统分区使硬盘前端有200M空间再新建或者调整。因为MAC系统安装必须满足EFI分区大于200M才可以。
3、新建MAC系统分区，这个步骤非常重要，如果不新建在一下个步骤安装MAC就只能整盘格式化，创建MAC分区是无损安装的核心。根据个人要求调整好Windows系统和其他分区，再将剩余硬盘空间全部新建为苹果分区，新建任选MAC类型分区格式都可以（此处我选择的是HFS+）。这样下一个步骤去安装MAC系统就能识别到苹果分区，从而不需要格式整个硬盘。
4、安装MAC系统，系统安装完成后替换EFI分区的CLOVER。
5、从新启动重建缓存。
