### ISSUE TITLE
三星磁盘卡在正在估算剩余时间

### ISSUE THREAD

**Issue by hexiangyuan** [frezs/MateBook14-Hackintosh#18]
matebook 14 2020款
16g i7
磁盘是三星的512G
双系统安装引导正常，但是一直卡在 剩余12分钟后变成 正在估算剩余时间。

换了外置usb ssd安装成功。
内置磁盘不成功。

**Comment by riven-zou** [comment]
三星的硬盘不行，需要更换成其他的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HeXiangyuan <notifications@github.com&gt;
发送时间: 2020年5月13日 13:39
收件人: frezs/MateBook14-Hackintosh <MateBook14-Hackintosh@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[frezs/MateBook14-Hackintosh] 三星磁盘卡在正在估算剩余时间 (#18)





 
matebook 14 2020款
 16g i7
 磁盘是三星的512G
 双系统安装引导正常，但是一直卡在 剩余12分钟后变成 正在估算剩余时间。
 换了外置usb ssd安装成功。
 内置磁盘不成功。

**Comment by hexiangyuan** [comment]
> 三星的硬盘不行，需要更换成其他的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: HeXiangyuan <notifications@github.com&gt; 发送时间: 2020年5月13日 13:39 收件人: frezs/MateBook14-Hackintosh <MateBook14-Hackintosh@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[frezs/MateBook14-Hackintosh] 三星磁盘卡在正在估算剩余时间 (#18) matebook 14 2020款 16g i7 磁盘是三星的512G 双系统安装引导正常，但是一直卡在 剩余12分钟后变成 正在估算剩余时间。 换了外置usb ssd安装成功。 内置磁盘不成功。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hexiangyuan** [comment]
我这边用另外一个SSD，通过paragon hard disk manager 恢复安装，并且成功装在三星SSD里面，现在使用过程中暂时没有什么异常。
