### ISSUE TITLE
hidpi文件写入问题

### ISSUE THREAD

**Issue by K1ruo** [frezs/MateBook14-Hackintosh#3]
老哥，那个手动写hidpi文件写进去结果drm里面没有写进去的hidpi分辨率是怎么回事呢

**Comment by K1ruo** [comment]
这个clover的显卡驱动也有问题，视频和游戏会莫名黑屏然后卡死

**Comment by frezs** [comment]
Hidpi写入问题请使用Github一键开启补丁进行开启
