### ISSUE TITLE
OC引导后卡在白苹果logo，不读条

### ISSUE THREAD

**Issue by Lynch89** [frezs/MateBook14-Hackintosh#33]
计算机：matebook14 2020 i7 16g
前置动作:bios中安全启动和软件安全芯片两个项目已关闭、CFG已解锁、已修改dvmt至64mb、镜像刻录后EFI文件已替换。
问题：U盘启动后卡在白苹果logo，并且不读条。

请问下是什么原因呢，十分感谢！

**Comment by suiyuekebo** [comment]
请问您解决了吗？我也遇到同样的问题。还有就是华为的bios里面选项太少，CFG什么的根本找不到，您是从哪里关的呀

**Comment by Lynch89** [comment]
已成功安装上。正常使用。我是使用下面的项目安装成功的，目前OC、Monterey和各项驱动都自己更新做最新了。
项目：https://github.com/Tecyang/matebook142020-OpenCore-Hackintosh
CFG解锁看这个项目：https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh

**Comment by Lynch89** [comment]
> 请问您解决了吗？我也遇到同样的问题。还有就是华为的bios里面选项太少，CFG什么的根本找不到，您是从哪里关的呀

已成功安装上。正常使用。我是使用下面的项目安装成功的，目前OC、Monterey和各项驱动都自己更新做最新了。
项目：https://github.com/Tecyang/matebook142020-OpenCore-Hackintosh
CFG解锁看这个项目：https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh

**Comment by Lynch89** [comment]
> 请问您解决了吗？我也遇到同样的问题。还有就是华为的bios里面选项太少，CFG什么的根本找不到，您是从哪里关的呀

已成功安装上。正常使用。我是使用下面的项目安装成功的，目前OC、Monterey和各项驱动都自己更新做最新了。
项目：https://github.com/Tecyang/matebook142020-OpenCore-Hackintosh
CFG解锁看这个项目：https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh
